# PostgreSQL 설정 및 테스트를 위한 yml
# - 무료 DB인 MySql 은 오라클에 인수되어 소유권 및 유료 전환에 대한 논쟁이 있으므로,
#  같은 무료이면서 오라클보다 강력한 성능을 보여주고 사용이 간편한 PostgreSQL 을 우선 적용해본다.
# - JPA 를 사용하는 프로젝트의 경우 DB 를 바꾸게 되었을 때 큰 수정이 필요하지 않으므로, 부담없이 적용할 수 있다.

# 이 설정을 적용하기까지 남은 과정
# 1. 이메일 인증을 실패했을 경우, 다시 이메일을 보내주기 위한 링크 및 페이지
# 2. 이메일을 연속적으로 보낼 수 있게 되면 자원낭비가 심하므로, 1시간에 한 번만 재전송할 수 있는 로직 작성
# 3. 이메일로 받은 토큰 값으로 접속하게 되면 패스워드 없이도 로그인할 수 있는 기능

spring:
  jpa:
    hibernate:
      ddl-auto: update # data 가 삭제되지 않도록 설정
    properties:
      hibernate:
        format_sql: true

# PostgreSQL 접속 계정 정보
  datasource:
    url: jdbc:postgresql://localhost:5434/xmalldb
    username: admin
    password: testpass

# 메일을 보내주는 서버로 Gmail 을 이용
# 하루 최대 메일 수에 제한이 있는 것 같지만, 프로젝트 용도로는 충분할 것 같다.
  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.haril07@gmail.com
    password: dqzehqwgvyqnaaxf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true