spring:
#  DB 설정하기 전엔 아래 옵션을 비활성화하기
#  -----
<<<<<<< HEAD
 # datasource:
   # url: jdbc:h2:tcp://localhost/~/xmall
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
=======
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/xmall
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
>>>>>>> 4fb6d60a4e38d033a25033d4b68be7e6a16dbd13
#  -----
#  thymeleaf:
#    cache: false
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

# 8083 포트 사용 시 활성화
#server.port: 8083
